config/routes.rb
Rails.application.routes.draw do

  root                              'home#index'

  get   'about'                 =>  'home#about'
  get   'faq'                   =>  'home#faq'
  get   'contact'               =>  'home#contact'

  resources :prerequisites
  resources :courses

end

app/models/course.rb
class Course < ActiveRecord::Base

  has_one :prerequisite, dependent: :destroy
  belongs_to :program
  
end

app/models/grade.rb
class Grade < ActiveRecord::Base
end

app/models/operator.rb
class Operator < ActiveRecord::Base
end

app/models/prerequisite.rb
require 'tree'

class Prerequisite < ActiveRecord::Base
  belongs_to :course

  def print_tree(t)
    if t.has_children?
      if t.content.operator == Operator.where(name: "and").first.id
        op = " and "
      else
        op = " or "
      end
      return "(" + self.print_tree(t['left'].content) + op + self.print_tree(t['right'].content) + ")"
    else
      p = t.content
      c = Course.find(p.operandA).name
      g = Grade.find(p.operandB).name
      return "(" + c + " >= " + g + ")"
    end
  end

  def descendant_tree
    if has_children?
      l, r = children
      node = Tree::TreeNode.new(id.to_s, self)
      node << Tree::TreeNode.new("left", l.descendant_tree)
      node << Tree::TreeNode.new("right", r.descendant_tree)
      return node
    else
      node = Tree::TreeNode.new(id.to_s, self)
      return node
    end
  end

  def children
    return [Prerequisite.find(operandA), Prerequisite.find(operandB)]
  end

  def has_children?
    # TODO: don't have to find 'and' and 'or' operator every time this method is called.
    # What a poor ORM ActiveRecord... does not it support 'or' method?
    ids = Operator.where("name = 'and' or name = 'or'").all.map { |op| op.id }
    return ids.include?(operator)
  end
end

app/models/program.rb
class Program < ActiveRecord::Base

  has_many :courses
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :set_course, only: [:show, :edit, :update, :destroy]

  # GET /courses
  # GET /courses.json
  def index
    @courses = Course.all
  end

  # GET /courses/1
  # GET /courses/1.json
  def show
  end

  # GET /courses/new
  def new
    @course = Course.new
  end

  # GET /courses/1/edit
  def edit
  end

  # POST /courses
  # POST /courses.json
  def create
    @course = Course.new(course_params)

    respond_to do |format|
      if @course.save
        format.html { redirect_to @course, notice: 'Course was successfully created.' }
        format.json { render :show, status: :created, location: @course }
      else
        format.html { render :new }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /courses/1
  # PATCH/PUT /courses/1.json
  def update
    respond_to do |format|
      if @course.update(course_params)
        format.html { redirect_to @course, notice: 'Course was successfully updated.' }
        format.json { render :show, status: :ok, location: @course }
      else
        format.html { render :edit }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /courses/1
  # DELETE /courses/1.json
  def destroy
    @course.destroy
    respond_to do |format|
      format.html { redirect_to courses_url, notice: 'Course was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_course
      @course = Course.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def course_params
      params.require(:course).permit(:name, :description)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
  end

  def about
  end

  def faq
  end

  def contact
  end
  
end

app/controllers/prerequisites_controller.rb
class PrerequisitesController < ApplicationController
  before_action :set_prerequisite, only: [:show, :edit, :update, :destroy]

  # GET /prerequisites
  # GET /prerequisites.json
  def index
    @prerequisites = Prerequisite.all
  end

  # GET /prerequisites/1
  # GET /prerequisites/1.json
  def show
  end

  # GET /prerequisites/new
  def new
    @prerequisite = Prerequisite.new
  end

  # GET /prerequisites/1/edit
  def edit
  end

  # POST /prerequisites
  # POST /prerequisites.json
  def create
    @prerequisite = Prerequisite.new(prerequisite_params)

    respond_to do |format|
      if @prerequisite.save
        format.html { redirect_to @prerequisite, notice: 'Prerequisite was successfully created.' }
        format.json { render :show, status: :created, location: @prerequisite }
      else
        format.html { render :new }
        format.json { render json: @prerequisite.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /prerequisites/1
  # PATCH/PUT /prerequisites/1.json
  def update
    respond_to do |format|
      if @prerequisite.update(prerequisite_params)
        format.html { redirect_to @prerequisite, notice: 'Prerequisite was successfully updated.' }
        format.json { render :show, status: :ok, location: @prerequisite }
      else
        format.html { render :edit }
        format.json { render json: @prerequisite.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /prerequisites/1
  # DELETE /prerequisites/1.json
  def destroy
    @prerequisite.destroy
    respond_to do |format|
      format.html { redirect_to prerequisites_url, notice: 'Prerequisite was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_prerequisite
      @prerequisite = Prerequisite.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def prerequisite_params
      params.require(:prerequisite).permit(:operator, :operandA, :operandB)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/prerequisites_helper.rb
module PrerequisitesHelper
end

app/views/courses/_form.html.erb
<%= form_for(@course) do |f| %>
  <% if @course.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@course.errors.count, "error") %> prohibited this course from being saved:</h2>

      <ul>
      <% @course.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/courses/edit.html.erb
<h1>Editing Course</h1>

<%= render 'form' %>

<%= link_to 'Show', @course %> |
<%= link_to 'Back', courses_path %>

app/views/courses/index.html.erb
<p id="notice"><%= notice %></p>

<% @page_header="Listing Courses" %>

    <% @courses.each do |course| %>

      <hr>
        <p><a data-toggle="collapse" href="#course<%= course.id %>" class='course-name'><%= course.name %></a></p>

        <div id='<%= "course#{course.id}" %>' class="collapse">
          <p class='course-description-tag'>Description: </p>
          <p class='course-description'> <%= course.description %></p>
          <p class='course-prereq-tag'>Prerequisites: </p>
          <p class='course-prereq'>  <% if !course.prerequisite.blank? %>
              <%= course.prerequisite.print_tree(course.prerequisite.descendant_tree) %>

            <% else %>
              <%= "None" %>
            <% end %>
          </p>
        </div>

    <% end %>


<br>
<%= link_to 'New Course', new_course_path %>

app/views/courses/new.html.erb
<h1>New Course</h1>

<%= render 'form' %>

<%= link_to 'Back', courses_path %>

app/views/courses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @course.name %>
</p>
<% if not @course.prerequisite.nil? %>
<p>
  <strong>Prerequisites:</strong>
  <%= @course.prerequisite.print_tree(@course.prerequisite.descendant_tree) %>
</p>
<% end %>

<%= link_to 'Edit', edit_course_path(@course) %> |
<%= link_to 'Back', courses_path %>

app/views/home/about.html.erb
<% @page_title = "About" %>
<% @page_header = "About Us" %>

app/views/home/contact.html.erb
<% @page_title = "Contact" %>

<script type="text/javascript">
function clicked()
{
	alert("Thank you for your message. We'll get back to you within 24 hours. Have a nice day!");
}
</script>

<div id="left" style="margin-left:10%">

<div class="fieldset" style ="margin-top:70px">
        <h2 class="title" style ="font-size:20px; margin-left:110px">SEND A MESSAGE</h2><br/>
        <ul>
            <li>
		<label for="name" class="title">Full Name</label>
            </li>
	    <li>
                    <div class="input-box">
                        <input name="name" id="name" title="Name" value="" placeholder ="preffered name(required)" class="login-form-input fk-input" type="text">
                    </div></br>
	   </li>
	   <li>
		<label for="email" class="title">E-MAIL</label>
	   </li>
	   <li>
                <div>
                    
                    <div class="input-box">
                        <input name="email" id="email" title="Email" value="" placeholder="someone@xyz.com(required)" class="login-form-input fk-input" type="text">
                    </div>
                </div>
            </li>
            <li>
		<label for="telephone" class="title">TELEPHONE</label>
	    </li>
	    <li>
                <div class="input-box">
                    <input name="telephone" id="telephone" placeholder="phone number(optional)" title="Telephone" value="" class="login-form-input fk-input" type="text">
                </div>
            </li>
	    <li>
		<label for="comment" class="title">MESSAGE</label>
	    </li>
            <li class="wide">
                
                <div class="input-box">
                    <textarea name="comment" id="comment" palceholder="Message(required)" title="Comment" class="login-form-input fk-input" cols="5" rows="3"></textarea>
                </div>
            </li>
		
		<li>
			<input type="Submit" onclick="clicked()" text="Submit" class="submit-btn"/>
		</li>
        </ul>
    </div>

</div>


<div id="center">
<div class="vr">&nbsp;</div>
</div>
<div id="right">
<div class="fieldset" style ="margin-top:70px">
        <h2 class="title" style ="font-size:20px; margin-left:110px">WRITE TO US</h2><br/>
        <ul >
	    
            <li style= "margin-top:40px;">
            
		<label for="block" class="address">MSC11 6325</label>
            </li>
	    <li>
                <label for="street" class="address">1 University of New Mexico</label>
	   </li>
	   <li>
		<label for="city" class="address"> Albuquerque </label>
	   </li>
	   <li>
                <label for="state" class="address"> New Mexico - 87131 </label>
            </li>
		</br>
            <li>
		<label class="address"> fax: (505) 456 0001 </label>
	    </li>
	  
        </ul>
    </div>
</div>

app/views/home/faq.html.erb
<% @page_title = "FAQs" %>

<div>
	<ul>
	<li>
		<image style="margin-left:15%" src='http://www.firstaiddepot.com/faq2.jpg'/>
	</li>
	<li>
		<label class="question" > What should I consider when selecting classes? </label>
	</li>
	<li>
		<p>Make sure you have enough mathematics/science classes for graduation requirements. Check with the appropriate teacher for advice about the workload of various electives. Consider expectations of colleges. If you are interested more in engineering, you may want to focus on physics and chemistry; if pre-med is a consideration, focus on chemistry electives.</p>
	</li>
	<li>
		<label class="question">What do colleges expect?</label>
	</li>
	<li>
		<p>While all colleges are not the same in terms of admission requirements, there are definite similarities about the academic basics colleges expect in order for a student to be competitive for admission. Below are some of the general admission requirements for a state university, a selective small liberal arts college, and an Ivy League school. These are to be used as guidelines only as specific departments/specialized majors within the schools themselves may have additional requirements for a student to complete to remain competitive.</p>
	</li>
	<li>
		<label class="question">Is this a required course?</label>
	</li>
	<li>
		<p>Most colleges and universities have specific college courses that all first-year students to take. You should be able to find out what these classes are in a student handbook or similar informational publication.There are also certain classes you will be required to take to fulfill your college major and college minor. For example, an English major may be required to take a certain number of classes in fields like British Literature, Post-Colonial Literature, and more.</p>
	</li>
	<li>
		<label class="question"> Are there prerequisites for this course? </label>
	</li>
	<li>	
		<p>Some higher level college classes have prerequisites, or specific classes that a student must take before he or she is permitted to take a higher level course. For example, if you want to take Calculus II, you may first have to fulfill the prerequisite of taking Calculus I.</p>
	</li>
	<li>
		<label class="question"> When does this course meet?</label>
	</li>
	<li>	
		<p>In high school, most students don’t have to consider the time or day of the week a class is offered. When choosing courses at college, however, it’s important to take scheduling into account.</p>
	</li>
	<li>
		<label class="question">How many students are in the class?</label>
	</li>
	<li>	
		<p>If you would prefer courses that allow for more interaction between students and face-to-face time with professors, then smaller classes may be for you. If, on the other hand, you would prefer to primarily listen to lectures instead of class participation, then choosing courses with a larger class size may be advisable.</p>
	</li>
	</ul>
</div>

app/views/home/index.html.erb
<% @page_title = "Homepage" %>
<script>
var animate_i = 0;
var animate_array = ["<image src='http://www.unm.edu/features/2015/graduation-2015.jpg'/>", "<image src ='http://www.unm.edu/features/2015/ecuador.jpg' />", "<image src='http://www.unm.edu/features/2015/food-pantry.jpg' />", "<image src='http://www.unm.edu/features/2015/receiver.jpg' />", "<image src='http://www.unm.edu/features/2015/vet.jpg' />"];
var animate_elem;
function animateNext(){
	animate_i++;
	animate_elem.style.opacity= 0;
	if(animate_i>animate_array.length - 1 ){
		animate_i =0;
	}
	setTimeout('animateSlide()',1000);
}
function animateSlide(){
	animate_elem.innerHTML = animate_array[animate_i];
	animate_elem.style.opacity = 1;
	setTimeout('animateNext()',3000);
}
</script>
<div style="width:128.5%;height:420px;background-color:#c10037; margin-left:-10%">
	<div style="width:970px">
		<span id="animate"></span>
	</div>
	<div style="width:20%">
		<div>
			<a class="btn" style="  background: #DAA733;" href="/courses">All about courses at UNM!</a>
		</div>
		<div>
			<a class="btn" style="  background: #777D12;"  href="/courses">Choose your courses</a>
		</div>
		<div>
			<a class="btn" style="  background: #00356A;" href="/courses">Know the prerequisites</a>
		</div>	
	</div>
</div>
<div>
<p id="homeTitle" > Welcome to UNM’s Online Catalog </p>
<p style="margin-left:5%; margin-right:15%; font-family:arial;font-size:16px;">The online Catalog is the University’s primary, comprehensive single source of departmental, college and university-wide information related to academic programs. Courses, degree programs, and policies that govern progress towards completion of a degree are described in the Catalog. Students are responsible for knowing and understanding the contents of the Catalog they are following. The Catalog provides a broad spectrum of course information in a consistent format and is a fully searchable and user-friendly online Catalog.</br><br>Whether you are a prospective student or enrolled at UNM, you will find we have provided you with a powerful set of tools to help you quickly locate and track details for undergraduate and graduate programs and courses that are important to you. You also will find links to other useful information. Access to prior editions of the Catalog is available in the archives section of this site.</br></br>We think you will find using this online Catalog to be easy and enjoyable! </br></br><b>Disclaimer: </b>The University of New Mexico reserves the right to make changes in the course offerings, degree requirements, charges, regulations, and procedures contained herein as educational and financial considerations require, subject to and consistent with established procedures and authorizations for making such change.</p>
</div>
<script>
animate_elem = document.getElementById("animate"); 
animateSlide();
</script>

app/views/layouts/_header.html.erb
<% if !@page_header.blank? %>
  <div class="main_header container">
    <h1><%= @page_header %></h1>
    <% if !notice.blank? or !alert.blank? %>
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
    <% end %>
  </div>
<% end %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "The Calendar App", root_path, class: 'navbar-brand' %>
    </div>
    <div class="collapse navbar-collapse" id="myNavbar">
      <ul class="nav navbar-nav navbar-right">
  <li><%= link_to "Courses",      courses_path %></li>
        <li><%= link_to "About Us",     about_path %></li>
        <li><%= link_to "FAQ",          faq_path %></li>
        <li><%= link_to "Contact Us",   contact_path %></li>

      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= @page_title ? "Catalog | #{@page_title}" : "Catalog" %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="site-wrapper">
  <%= render 'layouts/navbar' %>
  <%= render 'layouts/header' %>
  <div class="container">
    <%= yield %>
  </div>
  <%= render 'layouts/footer' %>
</div>

</body>
</html>

app/views/prerequisites/_form.html.erb
<%= form_for(@prerequisite) do |f| %>
  <% if @prerequisite.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@prerequisite.errors.count, "error") %> prohibited this prerequisite from being saved:</h2>

      <ul>
      <% @prerequisite.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :operator %><br>
    <%= f.number_field :operator %>
  </div>
  <div class="field">
    <%= f.label :operandA %><br>
    <%= f.number_field :operandA %>
  </div>
  <div class="field">
    <%= f.label :operandB %><br>
    <%= f.number_field :operandB %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/prerequisites/edit.html.erb
<h1>Editing Prerequisite</h1>

<%= render 'form' %>

<%= link_to 'Show', @prerequisite %> |
<%= link_to 'Back', prerequisites_path %>

app/views/prerequisites/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Prerequisites</h1>

<table>
  <thead>
    <tr>
      <th>Operator</th>
      <th>Operanda</th>
      <th>Operandb</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @prerequisites.each do |prerequisite| %>
      <tr>
        <td><%= prerequisite.operator %></td>
        <td><%= prerequisite.operandA %></td>
        <td><%= prerequisite.operandB %></td>
        <td><%= link_to 'Show', prerequisite %></td>
        <td><%= link_to 'Edit', edit_prerequisite_path(prerequisite) %></td>
        <td><%= link_to 'Destroy', prerequisite, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Prerequisite', new_prerequisite_path %>

app/views/prerequisites/new.html.erb
<h1>New Prerequisite</h1>

<%= render 'form' %>

<%= link_to 'Back', prerequisites_path %>

app/views/prerequisites/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Operator:</strong>
  <%= @prerequisite.operator %>
</p>

<p>
  <strong>Operanda:</strong>
  <%= @prerequisite.operandA %>
</p>

<p>
  <strong>Operandb:</strong>
  <%= @prerequisite.operandB %>
</p>

<%= link_to 'Edit', edit_prerequisite_path(@prerequisite) %> |
<%= link_to 'Back', prerequisites_path %>